services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - APP_DATA_DIR=/app/data
    volumes:
      - ./data:/app/data
    command: ["uvicorn", "backend.app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

